language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - '7.3'
  - '7.4'

before_script:
  - cp .env.dist .env
  - flags="-o"
  - composer install $flags

script: composer run-script ci

after_success:
  - bash <(curl -s https://codecov.io/bash)
