language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - '7.4'

before_script:
  - flags="-o"
  - composer install $flags

script: php ./vendor/phpunit/phpunit/phpunit -c phpunit.xml.dist

after_success:
  - bash <(curl -s https://codecov.io/bash)